apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: webapp
spec:
  selector:
    matchLabels:
      app: webapp

  replicas: 1
  
  template: # template for pods
    metadata:
      labels:
        app: webapp
    spec:
      containers:
        - name: webapp
          image: priya123456/fleetman-webapp-dev:1.0      
