apiVersion: v1
kind: Service
metadata:
  name: fleetman-webapp
  

# This defines which pods are going to be represented by this service
# The service becomes the network endpoint for either other service or may be external users to connect to (browser)
spec:
  selector:
    app: webapp
    release: "1.0"

  ports:
  - name: http
    port: 8080
    nodePort: 30080  #nodeport value should be greater than 30000

  type: NodePort
  

